#!/bin/bash
# script to setup a python virtual environment and install pita with its required dependencies in it.
# requirements are:
#   - virtualenv is installed
#   - git is installed
#   - Pycluster-1.52.tar.gz is in directory Downloads
#   - pp-1.6.4.tar.gz is in directory Downloads
#$1 = pycluster
#$2 = parallel python

virtualenv -p /usr/bin/python2.7 virtEnv
. virtEnv/bin/activate
pip install pip --upgrade
pip install numpy
pip install $1
pip install $1
pip install git+https://github.com/simonvh/gimmemotifs.git
pip install git+https://github.com/simonvh/pita.git
pip install git+https://github.com/simonvh/fluff.git

mkdir maxentscan
cd maxentscan
git clone https://github.com/razZ0r/maxentscan.git
echo "Script done"
