#!/usr/bin/env python
#Author: Joris van Steenbrugge
#since: April 19
#Function: Takes the fasta entries from a single file and outputs them to individual files
import sys

try:
	file = open(sys.argv[1])
except:
	print("Provide an input file")
	sys.exit()

name = ""
seq = ""
for i in file:
	if ">" in i:
		if name != "":
			outfile = open(name+".fa","w")
			outfile.write(">"+name+"\n")
			outfile.write(seq)
		name = i.split(" ")[0].replace(">","")                
		seq = ""
	else:
		seq+=i

outfile = open(name+".fa","w")
outfile.write(">"+name+"\n")
outfile.write(seq)
