#!/usr/bin/env python

import sys

try:
	file = open(sys.argv[1])
except:
	print("Provide an input file")
	sys.exit()

name = ""
seq = ""
for i in file:
	if ">" in i:
		if name != "":
			outfile = open(name+".fa","w")
			outfile.write(">"+name+"\n")
			outfile.write(seq)
		name = i.split(" ")[0].replace(">","")
		seq = ""
	else:
		seq+=i

outfile.write(">"+name+"\n")
outfile.write(seq)
