#!/usr/bin/env python
from sys import argv


with open(argv[1]) as in_file:
    for line in in_file:
        line = line.rstrip()

        line = line.split()
        try:
            if "maker" in line[1]:
                print("\t".join(line))
        except IndexError:
            continue
