#!/usr/bin/env python
#Author: Joris van Steenbrugge
#Since: March 16
#Function: Calculates the sizes per chromosome/contig in number of basepairs from a single fasta file

import sys
file = open(sys.argv[1])
outfile = open(sys.argv[2],"w")

name = ""
seq = ""
for i in file:
	if ">" in i:
		if name != "":
			outfile.write(name +"\t"+str(len(seq))+"\n")
		name = i.split(" ")[0].replace(">","")
		seq = ""
	else:
		seq+=i.strip()

outfile.write(name +"\t"+str(len(seq))+"\n")




