#!/usr/bin/env python3

from sys import argv
from sys import exit
from Bio import SeqIO
import string
import random

NCHAR = 6

try:
    filename = argv[1]
except:
    exit("usage: ./script <file.fa|file.tree>")

if filename.endswith('fa') or filename.endswith('.fasta'):
    mode = 'fasta'
else:
    mode = 'tree'


if mode == 'fasta':
    out_fasta = open('converted_fasta.fa', 'w')
    out_map = open('id_maptable.txt', 'w')

    for record in SeqIO.parse(filename, mode):
        random_id = ''.join( [random.choice(string.ascii_lowercase) for i in range(NCHAR) ])
        seq = str(record.seq)
    
        out_map.write(f'{random_id}\t{record.id}\n')

        out_fasta.write(f'>{random_id}\n{seq}\n')


    out_fasta.close()
    out_map.close()
elif mode == 'tree':
    id_map = {}
    with open('id_maptable.txt','r') as map_file:
        for line in map_file:
            line = line.strip().split('\t')
            id_map[line[0]] = line[1] 

    with open(filename) as in_tree:
        tree_line = ''.join(in_tree.readlines())
        for id in id_map.keys():
            tree_line = tree_line.replace(id, id_map[id])

        print(tree_line)                
