#!/bin/bash
# This script accepts sra files (compressed fastq) and converts them to a bigWiggle, alongside with sorted, indexed bam files.
# mapping is done based on the xenopus tropicalis xt9_0 genome in this example

# sample command: rna2bw <filename>

function sraSplit {
	echo "Going to convert sra2fastq"
	fastq-dump $1 --split-files # -X 100
	mapping $1
}

function mapping {
	file1=$(basename $1 .sra)_1.fastq
	file2=$(basename $1 .sra)_2.fastq
	/home/jsteenbrugge/tools/hisat2-2.0.1-beta/hisat2 --very-fast  -p 12 -q -x /home/jsteenbrugge/data/genomeXenbase/index -1 $file1 $file2 -S $(basename $1 .sra).sam
	rm $file1
	rm $file2
	echo "Mapping done, going to convert sam2bam..."
	sam2bam $1
}

function  sam2bam {
	samtools view $(basename $1 .sra).sam -bS > $(basename $1 .sra).bam
	rm $(basename $1 .sra).sam
	echo "sam converted to bam, going to sort the bam file now..."
	sorting $1
}

function sorting {
	samtools sort -@ 4 -m 10G $(basename $1 .sra).bam $(basename $1 .sra)_sorted
	rm $(basename $1 .sra).bam
	echo "bam sorted, going to convert to bigwigg now..."
	#bamTobw $1
}

#bigWiggle files can be used for visualization in the UCSC genome browser
function bamTobw {
	bam2bw -D -S -i $(basename $1 .sra)_sorted.bam -o $(basename $1 .sra).bw
	echo "---finished---"
}


sraSplit $1
