#!/bin/bash
# This script accepts various types (sra,fastq,sam,bam,sorted bam) and converts them to a bigWig 
# mapping is done based on the xenopus tropicalis xt9_0 genome
#
# missing: chip-seq implementation
# sample command: file2bw <filename>

function sraSplit {
	echo "Going to convert sra2fastq, ga maar alvast koffie halen..."
	fastq-dump $1 --split-files  #-X 100 for testing
	mapping $1
}

function mapping {
	file1=$(basename $1 .sra)_1.fastq
	file2=$(basename $1 .sra)_2.fastq
	/home/jsteenbrugge/tools/hisat2-2.0.1-beta/hisat2 --very-fast  -p 16 -q -x /home/jsteenbrugge/data/genomeXenbase/index -1 $file1 $file2 -S $(basename $1 .sra).sam
	rm $file1
	rm $file2
	echo "Mapping done, going to convert sam2bam..."
	sam2bam $1
}

function  sam2bam {
	samtools view $(basename $1 .sra).sam -bS > $(basename $1 .sra).bam
	rm $(basename $1 .sra).sam
	echo "sam converted to bam, going to sort the bam file now..."
	sorting $1
}

function sorting {
	samtools sort -@ 4 -m 10G $(basename $1 .sra).bam $(basename $1 .sra)_sorted
	rm $(basename $1 .sra).bam
	echo "bam sorted, going to convert to bigwigg now..."
	bamTobw $1
}

function bamTobw {
	bam2bw -D -S -i $(basename $1 .sra)_sorted.bam -o $(basename $1 .sra).bw
	echo "---finished---"
}

function test {
	echo "test"
}

if [[ "$1" == *".sra"* ]]
then
	sraSplit $1
fi
if [[ "$1" == *".fastq" ]]
then
	mapping $1
fi
if [[ "$1" == *".sam" ]]
then
	sam2bam $1
fi
if [[ "$1" == *".bam" ]]
then
	if [[ "$1" == *"sorted"* ]]
	then
		bamTobw $1
	else
		sorting $1
	fi
fi
if [[ "$1" == "" ]]
then
	echo "No input file specified"
fi


