#!/usr/bin/env python
import sys
import argparse

h3k4dir = None
bedFiles = None

def argsParse():
	global h3k4dir, bedFiles

	p = argparse.ArgumentParser()
	p.add_argument("-d", dest="directory", help="Directory with H3K4me3 bam files", required=True)
	p.add_argument("-b", dest="bedFiles",nargs="+", help="bedfile produced by pita", required=True)
	args = p.parse_args()

	#retrieving the files
	h3k4dir = args.directory
	bedFiles = ars.bedFiles
